#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Default_greeting:
  path: /greeting
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'hello'
    permanent: true
    keepQueryParams: true